---
driver:
  name: vagrant
  vagrantfile_erb: './Vagrantfile.erb'

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[dotpromo-rails-box::default]
      - recipe[minitest-handler]
    attributes:
      dotpromo-rails-box:
        app_name: 'test'
        app_dir: '/srv/app/test_app'
