name 'dotpromo-rails-box'
maintainer '.PROMO Inc.'
maintainer_email 'Alexander Simonov <alex@simonov.me>'
license 'MIT'
description 'Installs/Configures rails app'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.2.0'

supports 'ubuntu', '>= 12.04'
supports 'centos', '>= 6.5'

depends 'dotpromo-ruby-box'
depends 'dotpromo-postgresql-box'
depends 'database'
depends 'openssl'
depends 'nginx'
depends 'redisio'
depends 'java'
depends 'runit'
depends 'simple_iptables'
depends 'ntp', '~> 1.7.0'
